#!/bin/bash

FM=konqueror #mc 
MOUNT_ROOT=/media/samba
ER="kdialog --error" #echo

smbpath=`ruby -e "require 'cgi'; puts CGI.unescape('$(echo "$@" | sed "s|'|%27|g")')"`
if [[ "$smbpath" =~ smb://(.*?) ]]; then
    host=`echo "$smbpath" | sed "s|smb://||;s|/.*||"`
    smbshare=`echo "$smbpath" | sed "s|smb://$host||;s|^/||;s|/.*||"`
else
    echo "$smbpath: Wrong syntax"
    exit 1
fi

list=`smbclient -gNL "$host" 2>/dev/null | sed -n 's/^Disk|\([^|]*\)|.*/\1/p'`
if [[ $list == "" ]]; then 
    error="$host: No such host"
else
    if [ "$smbshare" != "" -a "`echo "$list" | grep -w "$smbshare"`" == "" ]; then error="$smbshare: No such share"; fi
fi

if [[ "$error" = "" ]]; then
    echo "$list" | while read share; do
        mount_dir=$MOUNT_ROOT/$host/$share
        mkdir -p "$mount_dir"
        result=`sudo mount.cifs "//$host/$share" "$mount_dir" -o guest,nounix`
        if [ "$result" != "" -a "$share" == "$smbshare" ]; then error="$result"; fi
    done
fi

if [[ "$error" == "" ]]; then
    localpath="$MOUNT_ROOT/`echo "$smbpath" | sed 's|smb://||'`"
    if [ -e "$localpath" ]; then 
        $FM "$localpath"
    else
    	$ER "$smbpath: Path does not exist"
    fi
else
    $ER "$error"
fi

echo "$list" | while read share; do
    sudo umount.cifs "$MOUNT_ROOT/$host/$share" 2> /dev/null
done

rm -r --one-file-system "$MOUNT_ROOT/$host" 2> /dev/null
